site_name: Lacerta

nav:
  - Home: index.md
  - Problem Statement: problem_statement.md
  - Proposed Solution: proposed_solution.md
  - System Architecture: system_architecture.md
  - System Development: system_development.md
theme: readthedocs